name: tests

on:
  push:
  pull_request:

jobs:
  pocketstep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cmake -S pocketstep -B build/pocketstep
      - run: cmake --build build/pocketstep
      - run: ctest --test-dir build/pocketstep --output-on-failure
